// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package inner

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RaftClient is the client API for Raft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftClient interface {
	// Sends a Join Request
	JoinRequest(ctx context.Context, in *JoinReq, opts ...grpc.CallOption) (*JoinRsp, error)
	TransHttpRequest(ctx context.Context, in *TransHttpReq, opts ...grpc.CallOption) (*TransHttpRsp, error)
}

type raftClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftClient(cc grpc.ClientConnInterface) RaftClient {
	return &raftClient{cc}
}

func (c *raftClient) JoinRequest(ctx context.Context, in *JoinReq, opts ...grpc.CallOption) (*JoinRsp, error) {
	out := new(JoinRsp)
	err := c.cc.Invoke(ctx, "/inner.Raft/JoinRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) TransHttpRequest(ctx context.Context, in *TransHttpReq, opts ...grpc.CallOption) (*TransHttpRsp, error) {
	out := new(TransHttpRsp)
	err := c.cc.Invoke(ctx, "/inner.Raft/TransHttpRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftServer is the server API for Raft service.
// All implementations must embed UnimplementedRaftServer
// for forward compatibility
type RaftServer interface {
	// Sends a Join Request
	JoinRequest(context.Context, *JoinReq) (*JoinRsp, error)
	TransHttpRequest(context.Context, *TransHttpReq) (*TransHttpRsp, error)
	mustEmbedUnimplementedRaftServer()
}

// UnimplementedRaftServer must be embedded to have forward compatible implementations.
type UnimplementedRaftServer struct {
}

func (*UnimplementedRaftServer) JoinRequest(context.Context, *JoinReq) (*JoinRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinRequest not implemented")
}
func (*UnimplementedRaftServer) TransHttpRequest(context.Context, *TransHttpReq) (*TransHttpRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransHttpRequest not implemented")
}
func (*UnimplementedRaftServer) mustEmbedUnimplementedRaftServer() {}

func RegisterRaftServer(s *grpc.Server, srv RaftServer) {
	s.RegisterService(&_Raft_serviceDesc, srv)
}

func _Raft_JoinRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).JoinRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inner.Raft/JoinRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).JoinRequest(ctx, req.(*JoinReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_TransHttpRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransHttpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).TransHttpRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inner.Raft/TransHttpRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).TransHttpRequest(ctx, req.(*TransHttpReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Raft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inner.Raft",
	HandlerType: (*RaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinRequest",
			Handler:    _Raft_JoinRequest_Handler,
		},
		{
			MethodName: "TransHttpRequest",
			Handler:    _Raft_TransHttpRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inner.proto",
}
